name: MastersWorkTest

on:
  push:
    branches: ['master']
  
  workflow_dispatch:
  
env: 

  APP_NAME: CDICDMastersWorkTest
  REPO_USER: petyastoleru
  REPO_NAME: VulnerableApp

jobs: 
  pre-build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: scan code for vulnerabilities
      run: | 
        echo running scan on $(pwd)
        export SCAN_URL=https://dev.clouddefenseai.com
        cdefense online --api-key=c8f244ea-f0d2-4094-9220-104f04a4d8e4 --repository-url=https://github.com/${{ env.REPO_USER }}/${{ env.REPO_NAME }}.git
        
  build:
    runs-on: ubuntu-20.04
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
